version: '2'
services:
    db:
        image: postgres:10
        environment:
            - "POSTGRES_USER=kuter"
            - "POSTGRES_PASSWORD=111"
            - "POSTGRES_DB=nn"
        ports:
            - "5434:5432"
        command: ["postgres", "-c", "log_statement=all"]
    percona:
      image: percona:5.6
      ports:
       - "3306:3306"
      volumes:
       - ./mysql.d:/etc/mysql/conf.d
       - ./mysql-data:/var/lib/mysql
       - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
       # - /var/lib/mysql
      environment:
       - MYSQL_USER=lazada
       - MYSQL_PASSWORD=rock4me
       - MYSQL_ROOT_PASSWORD=111
#    tracing:
#        image: jaegertracing/all-in-one:latest
#        environment:
#            - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"
#        ports:
#          - "5775:5775/udp"
#          - "16686:16686"
#          - "6831:6831/udp"
#          - "6832:6832/udp"


